<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Customform
 */
?>
<?php
/** @var Amasty\Customform\Block\Init $block */

use Amasty\Customform\Model\Config\GdprCustomform;

$formId = $block->getFormId();
$isSurvey = $block->isSurvey();
$usePopup = $block->isPopupUsed();
?>

<?php if ($usePopup): ?>
    <div class="amform-parent">
        <div class="amform-popup" data-form-id=<?= (int)$formId ?>>
<?php endif; ?>

<form class="rendered-form amform-form <?= /* @noEscape */ ($usePopup) ? 'amform-content' : '' ?> <?= $block->escapeHtml($block->getAdditionalClasses()) ?>"
      id="amform-form-<?= (int)$formId ?>"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      data-mage-init='{"validation": {"ignore" : ".amcform-hidden-field, .amcform-hidden-page, :hidden:not(.amform-rating)"}}'
      enctype="multipart/form-data" method="post">

    <input name="form_key" type="hidden" value="<?= $block->escapeHtml($block->getFormKey()) ?>" />
    <input name="form_id" type="hidden" value="<?= (int)$formId ?>" />
    <input name="is_survey" type="hidden" value="<?= (int)$isSurvey ?>" />
    <div class="amform-form-fieldset fieldset">
        <div class="insert-container fields"></div>
        <?php if ($block->isGDPREnabled()): ?>
            <div class="field required amform-hide-formload control amcform-gdpr" data-amcform-js="gdpr" style="display: none">
                <label class="label">
                    <input class="amform-checkbox"
                           type="checkbox"
                           name="gdpr"
                           data-id="amcustom-form-gdpr-<?= (int)$formId ?>"
                           id="amcustom-form-gdpr-<?= (int)$formId ?>"
                           title="<?= $block->escapeHtml(__('GDPR')); ?>"
                           data-validate="{required:true}"
                           value="1"
                           disabled>
                    <?= /* @noEscape */ $block->getGDPRText(); ?>
                </label>
            </div>
        <?php endif; ?>
        <?php $gdprCheckboxesHtml = $block->getGdprCheckboxHtml($formId . GdprCustomform::CUSTOM_FORM); ?>
        <?php if (!empty($gdprCheckboxesHtml)): ?>
            <?= /** @noEscape */ $gdprCheckboxesHtml ?>
        <?php endif; ?>
    </div>
    <?php if ($usePopup): ?>
        <div class="amform-popup-close">
            <span class="amform-close">&times;</span>
        </div>
    <?php endif; ?>
</form>

<?php if ($usePopup): ?>
    </div>
        <div data-amform-show="<?= (int)$formId ?>" class="amform-show">
            <button class="action primary"><?= $block->escapeHtml($block->getTriggerPopup()) ?></button>
        </div>
    </div>
<?php endif; ?>

<script type="text/javascript">
    <?php if ($block->isUseGoogleMap()): ?>
        require([
            'https://maps.googleapis.com/maps/api/js?libraries=places&key=<?= $block->escapeHtml($block->getGoogleKey()) ?>'
        ], function () {
        });
    <?php endif; ?>

    require([
        'jquery',
        'Amasty_Customform/js/form-render',
        'Amasty_Customform/js/form-session',
        'Amasty_Customform/js/am-google-map',
        'Amasty_Customform/js/form-init'
    ], function ($) {
        var renderedFormContainer = $('#amform-form-<?= (int)$formId ?> .insert-container'),
            renderedForm;

        $('body').addClass('amform-body');

        renderedFormContainer.formRender(
            <?= (int)$formId ?>,
            <?= /* @noEscape */ $block->getFormDataJson() ?>,
            <?= (int)$isSurvey ?>,
            function () {
                renderedForm = $('[data-amcform-js="multi-page"]');

                if (renderedForm.length) {
                    renderedForm.amFormInit();
                    renderedForm.amFormSession(
                        {
                            'urlSession': "<?= $block->escapeUrl($block->getSessionUrl()) ?>",
                            'formId': <?= (int)$formId ?>
                        });
                    renderedForm.trigger('contentUpdated');
                }
            }
        );
    });
</script>
