<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Customform
 */
?>
<?php
/** @var \Amasty\Customform\Block\Adminhtml\Data\Edit\Answer $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<section class="admin__page-section request-view-information">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */ __('Information') ?></span>
    </div>
    <div class="admin__page-section-content">
        <table class="admin__table-secondary request-information-table">
            <?php foreach ($block->getInformationData() as $data): ?>
                <tr>
                    <th><?= $escaper->escapeHtml($data['label']) ?></th>
                    <td><?= /* @noEscape */ $data['value'] ?></td>
                </tr>
            <?php endforeach;?>
        </table>
    </div>
</section>
<section class="admin__page-section request-view-data">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */ __('Data') ?></span>
    </div>
    <div class="admin__page-section-content">
        <table class="admin__table-secondary request-information-table">
            <?php foreach ($block->getResponseData() as $key => $data): ?>
                <tr>
                    <th><?= $escaper->escapeHtml($data['label']) ?></th>
                    <td>
                        <?php if ($data['type'] == 'googlemap'): ?>
                            <div id="map-<?= $escaper->escapeHtmlAttr($key) ?>" class="fb-googlemap"></div>
                            <script type="text/javascript">
                                require([
                                    'jquery',
                                    'https://maps.googleapis.com/maps/api/js?libraries=places&key=<?= $escaper->escapeUrl($block->getGoogleKey()) ?>',
                                    'Amasty_Customform/js/am-google-map'
                                ], function ($) {
                                    $('#map-<?= $escaper->escapeHtmlAttr($key) ?>').amGoogleMap(Object.assign(
                                        <?= /* @noEscape */ $data['value'] ?>,
                                        {
                                            'enabledMarker': false,
                                            'showFormattedAddress': true
                                        }
                                    ));
                                });
                            </script>
                        <?php else: ?>
                            <?= /* @noEscape */ $data['value'] ?>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach;?>
        </table>
    </div>
</section>
<section class="admin__page-section request-view-data">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */ __('Admin Response') ?></span>
    </div>
    <div class="admin__page-section-content">
        <table class="admin__table-secondary request-information-table">
            <?php foreach ($block->getAdminResponseData() as $data): ?>
                <tr>
                    <th><?= $escaper->escapeHtml($data['label']) ?></th>
                    <td><?= /* @noEscape */ $data['value']?></td>
                </tr>
            <?php endforeach;?>
        </table>
    </div>
</section>
<?php if ($block->isShowEmailSendingForm()): ?>
<section class="admin__page-section request-view-answer-section">
    <div id="request-view-answer" class="request-view-answer">
        <form class='am-send-email-form' action="<?= $escaper->escapeUrl($block->getSubmitUrl()) ?>" method="post">
            <input name="form_key" type="hidden" value="<?= $escaper->escapeHtml($block->getFormKey()) ?>" />
            <div class="request-answer-block">
                <div class="admin__field field-row">
                    <label class="admin__field-label"
                           for="email_text"><?= /* @noEscape */ __('Email Text') ?></label>
                    <div class="admin__field-control">
                        <textarea name="email_text"
                                  class="admin__control-textarea"
                                  rows="3"
                                  cols="5"
                                  id="email_text"></textarea>
                    </div>
                </div>
                <div class="admin__field">
                    <div class="review-actions">
                        <?= $block->getChildHtml('submit_button') ?>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>
<?php endif;?>
